org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.9

fabric_version=0.102.0+1.21

#fabric_kotlin_version=1.10.8+kotlin.1.9.0

modmenu_version=11.0.2
clothconfig_version=15.0.140
rei_version=16.0.788
pehkui_version=3.8.3
trinkets_version=3.10.0
#patchouli_version=1.20.6-87-FABRIC-SNAPSHOT
#inventorio_version=5134138
cardinal_components_version=6.1.1
#nbttt_version=3595757
#flk_version=3364215

mod_version = 1.13.1
maven_group = zabi.minecraft.extraalchemy
archives_base_name = extraalchemy-fabric
